### ISSUE TITLE
Logo not seen on Startpage and Adminpanel after upload

### ISSUE THREAD

**Issue by Toutzn** [Lan2Play/eventula-manager#666]
If you use no png logos, the file will be upload but does't seen on the pages:

```
eventula_manager_app         | 127.0.0.1 -  22/Nov/2023:16:19:54 +0100 "GET /index.php" 200
eventula_manager_app         | NOTICE: PHP message: [2023-11-22 15:19:55] production.ERROR: imagecreatefrompng(): &quot;storage/images/main/logo_main191.png&quot; is not a valid PNG file {"exception":"[object] (ErrorException(code: 0): imagecreatefrompng(): &quot;storage/images/main/logo_main191.png&quot; is not a valid PNG file at /web/html/app/Http/Controllers/Api/Images/WebpController.php:56)
eventula_manager_app         | [stacktrace]
eventula_manager_app         | #0 /web/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
eventula_manager_app         | #1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
eventula_manager_app         | #2 /web/html/app/Http/Controllers/Api/Images/WebpController.php(56): imagecreatefrompng()
eventula_manager_app         | #3 /web/html/app/Http/Controllers/Api/Images/WebpController.php(25): App\\Http\\Controllers\\Api\\Images\\WebpController->imagecreatefromfile()
eventula_manager_app         | #4 /web/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Api\\Images\\WebpController->convert()
eventula_manager_app         | #5 /web/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
eventula_manager_app         | #6 /web/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
eventula_manager_app         | #7 /web/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
eventula_manager_app         | #8 /web/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
eventula_manager_app         | #9 /web/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
eventula_manager_app         | #10 /web/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
eventula_manager_app         | #11 /web/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then()
eventula_manager_app         | #12 /web/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
```

**Comment by Toutzn** [comment]
on more: this issue could be the same for the users steam avatars eventually?

<img width="1183" alt="image" src="https://github.com/Lan2Play/eventula-manager/assets/3788105/7db07d70-43a6-4bb4-93c5-90cc7a887552">

**Comment by Apfelwurm** [comment]
fixed by https://github.com/Lan2Play/eventula-manager/pull/812
